# Generated by Django 2.2.6 on 2019-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='signUp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
